@startuml
!pragma layout smetana

Class Main{
}

Interface Menu{
public void ShowMenu()
}

Class StartMenu{
}

Class MainMenu{
}

Class User{
- String Username
- String Password
+ Login(String username, String password)
+ CreateAccount(String username, String password)
}

Class SearchHandler {
- String input
+ ArrayList<String> search(String input)
}

Class DataHandler{
+ fileReader(path)
+ saveMediaData(String title)
+ saveUserData(String username, String password)
}

Abstract Media{
- int releaseYear
- String name
- String category
- double rating
+ void watchLater(User user)
+ void removeFromWatchLater(User user)
+ void alreadyWatched(User user)
+ void watch()
}

Class Util{
- Scanner scanner
+ String PromptText(String msg)
+ int PromptChoice(String msg, ArrayList<String> list)
+ void displayMsg(String msg)
}

Class Movies{
public String toString()
}

Class Shows{
- ArrayList<Seasons>
- ArrayList<Episodes>
+ public String toString()
}

Main --> Menu
Menu --> StartMenu
Main --> Util
Main --> User
Menu --> MainMenu
Util --> Media
Media <|-- Shows
Media <|-- Movies
User --> DataHandler
DataHandler --> Media
SearchHandler --> MainMenu


@enduml